services:

  afa-postgres:
    container_name: postgres_afaloan
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init_databases.sql:/docker-entrypoint-initdb.d/init_databases.sql
    profiles:
      - allin
      - local

  afaloan:
    container_name: afaloan
    image: afaloan
    ports:
      - "8080:8080"
    build:
      context: "Afaloan"
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_URL: jdbc:postgresql://afa-postgres:5432/afaloan
      DB_USER: username
      DB_PASSWORD: password
    depends_on:
      - afa-postgres
    profiles:
      - allin