server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/afaloan}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
